# put the confuration which is repeating/common in all microservice
# eureka configuration for discovery client
eureka:
  client:
    fetch-registry: true  # by default these are true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka # it will use this eureka server url inorder to register with server
  instance:
    prefer-ip-address: true # it will prefer ip address
